#!/bin/bash

set -e

rm -rf CovidDB
mkdir CovidDB
cd CovidDB

# Download slug list (country names):
wget -O - https://api.covid19api.com/countries | tr '\{' '\n' |
    awk -F\" '{ print $8 }' | sed 's/united-states//' |
    sed '/^$/d' | sort > slugs

mkdir Countries
cd Countries
(sed 's#^#https://api.covid19api.com/total/country/#' ../slugs | wget -w 0.5 -nv -i -) || true

grep -l "\[]" * | while read file; do
    rm "${file}"
done

ls * > ../country_names

ls * | while read file; do
    tr '\{' '\n' < "${file}" | sed 's/T..:..:[^"]*"/"/' |
        sed '/^\[$/d' |
        awk -F\" 'NR==1 { print $38,$30,$32,$34,$36 } { print $40,$31,$33,$35,$37 }' |
        sed 's/[:,]//g' > "${file}.data"
    rm "${file}"
done

# Make an index of countries with data:
cd ..
ls Countries/* > country_index

rm slugs
